CREATE TABLE productos(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    img TEXT NOT NULL,
    nombre VARCHAR(200) NOT NULL,
    descripcion VARCHAR(400) NOT NULL,
    precio DECIMAL,
    createAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE vendedores(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    pass VARCHAR(100) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    createAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE usuarios(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    pass VARCHAR(100) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    createAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)