CREATE TABLE productos(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    img TEXT NOT NULL,
    nombre VARCHAR(200) NOT NULL,
    descripcion VARCHAR(400) NOT NULL,
    precio DECIMAL,
    createAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)